# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a23494ff2ec44dcd944b8acc032a0a64e303199cd1ba1c61883ac77b40870ad16867c7a0d3c75cc02bc114aca986be00d5132a3c23aba1d6aa627276634c80be

test:
  secret_key_base: 4b8ffd59573d4760aac21f94e64ec50c688fc4b77741939512787531b6e91d5ad9dcfd068490e7c1b257f31c9b980c679dd4549a3031990d8c288ed2d7d44eb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
